# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

version: 3.0
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: fzb.me,冯宗宝,冯宗宝的blog 

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


menu:
  home: /
  books: /reading
  travel: /travel
  tags: /tags
  about: /about     #添加这一行

menu_icons:
  enable: true
  home: home
  about: user     #添加这一行
  books: book
  travel: plane
  tags: tags
  message: comment #添加这一行

# Static files
#vendors: vendors
css: css
js: js
images: images

# Miscellaneous, enter the tracking ID for your Google Analytics
google_analytics: 
